In [1]:
import os
import pandas as pd

In [2]:
cwd = os.getcwd()
BASE_DIR = os.path.dirname(cwd)
DATA_DIR = os.path.join(BASE_DIR, 'data')

In [3]:
os.listdir(DATA_DIR)

['1995_boxofficemojo_rankings.csv',
 '1999_boxofficemojo_rankings.csv',
 '1983_boxofficemojo_rankings.csv',
 '1978_boxofficemojo_rankings.csv',
 '2006_boxofficemojo_rankings.csv',
 '2010_boxofficemojo_rankings.csv',
 '2017_boxofficemojo_rankings.csv',
 '.DS_Store',
 '2001_boxofficemojo_rankings.csv',
 '1984_boxofficemojo_rankings.csv',
 '1988_boxofficemojo_rankings.csv',
 '1992_boxofficemojo_rankings.csv',
 '2016_boxofficemojo_rankings.csv',
 '2000_boxofficemojo_rankings.csv',
 '1985_boxofficemojo_rankings.csv',
 '1989_boxofficemojo_rankings.csv',
 '1993_boxofficemojo_rankings.csv',
 '1994_boxofficemojo_rankings.csv',
 '1998_boxofficemojo_rankings.csv',
 '1979_boxofficemojo_rankings.csv',
 '1982_boxofficemojo_rankings.csv',
 '2007_boxofficemojo_rankings.csv',
 '2011_boxofficemojo_rankings.csv',
 '2002_boxofficemojo_rankings.csv',
 '2018_boxofficemojo_rankings.csv',
 '2014_boxofficemojo_rankings.csv',
 '1991_boxofficemojo_rankings.csv',
 '1987_boxofficemojo_rankings.csv',
 '1977_boxofficemojo_rankings.csv',
 '1980_boxofficemojo_rankings.csv',
 '1996_boxofficemojo_rankings.csv',
 '2013_boxofficemojo_rankings.csv',
 '2009_boxofficemojo_rankings.csv',
 '2005_boxofficemojo_rankings.csv',
 '1981_boxofficemojo_rankings.csv',
 '1997_boxofficemojo_rankings.csv',
 '2012_boxofficemojo_rankings.csv',
 '2008_boxofficemojo_rankings.csv',
 '2004_boxofficemojo_rankings.csv',
 '2003_boxofficemojo_rankings.csv',
 '2019_boxofficemojo_rankings.csv',
 '2015_boxofficemojo_rankings.csv',
 '2020_boxofficemojo_rankings.csv',
 '1990_boxofficemojo_rankings.csv',
 '1986_boxofficemojo_rankings.csv']

In [4]:
data = os.path.join(DATA_DIR, '1987_boxofficemojo_rankings.csv')
print(os.path.exists(data))

True

In [5]:
df = pd.read_csv(data)

In [6]:
df.head(n=10)

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,Fatal Attraction,"$320,145,693","$156,645,693",48.9%,"$163,500,000",51.1%
1,2,Beverly Hills Cop II,"$299,965,036","$153,665,036",51.2%,"$146,300,000",48.8%
2,3,Dirty Dancing,"$213,446,382","$63,446,382",29.7%,"$150,000,000",70.3%
3,4,Three Men and a Baby,"$167,780,960","$167,780,960",100%,-,-
4,5,"Good Morning, Vietnam","$123,922,370","$123,922,370",100%,-,-
5,6,Lethal Weapon,"$120,207,127","$65,207,127",54.2%,"$55,000,000",45.8%
6,7,The Secret of My Success,"$110,996,879","$66,995,879",60.4%,"$44,001,000",39.6%
7,8,Predator,"$98,268,458","$59,735,548",60.8%,"$38,532,910",39.2%
8,9,Moonstruck,"$80,640,528","$80,640,528",100%,-,-
9,10,The Untouchables,"$76,270,454","$76,270,454",100%,-,-