In [1]:
import os
import pandas as pd

In [20]:
cwd = os.getcwd()
BASE_DIR = os.path.dirname(cwd)
DATA_DIR = os.path.join(BASE_DIR, 'data')
CACHE_DIR = os.path.join(BASE_DIR, 'cache')
os.makedirs(CACHE_DIR, exist_ok = True)

In [3]:
for filename in os.listdir(DATA_DIR):
    print(filename)

2010_boxofficemojo_rankings.csv
2017_boxofficemojo_rankings.csv
.DS_Store
2016_boxofficemojo_rankings.csv
2011_boxofficemojo_rankings.csv
2018_boxofficemojo_rankings.csv
2014_boxofficemojo_rankings.csv
2013_boxofficemojo_rankings.csv
2012_boxofficemojo_rankings.csv
2019_boxofficemojo_rankings.csv
2015_boxofficemojo_rankings.csv
2020_boxofficemojo_rankings.csv

In [4]:
df = pd.read_csv(os.path.join(DATA_DIR, '2020_boxofficemojo_rankings.csv'))
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,The Eight Hundred,"$441,656,664","$331,279",<0.1%,"$441,325,385",99.9%
1,2,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%
2,3,Tenet,"$323,300,000","$48,300,000",14.9%,"$275,000,000",85.1%
3,4,Sonic the Hedgehog,"$306,766,470","$146,066,470",47.6%,"$160,700,000",52.4%
4,5,Dolittle,"$245,516,662","$77,047,065",31.4%,"$168,469,597",68.6%

In [5]:
df['Year'] = 2020

In [6]:
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,Year
0,1,The Eight Hundred,"$441,656,664","$331,279",<0.1%,"$441,325,385",99.9%,2020
1,2,Bad Boys for Life,"$426,505,244","$206,305,244",48.4%,"$220,200,000",51.6%,2020
2,3,Tenet,"$323,300,000","$48,300,000",14.9%,"$275,000,000",85.1%,2020
3,4,Sonic the Hedgehog,"$306,766,470","$146,066,470",47.6%,"$160,700,000",52.4%,2020
4,5,Dolittle,"$245,516,662","$77,047,065",31.4%,"$168,469,597",68.6%,2020

In [9]:
my_entire_data = pd.DataFrame

my_dataframes = []
csv_files = [x for x in os.listdir(DATA_DIR) if x.endswith(".csv")]

for filename in csv_files:
    print(filename)
    year = filename.replace("_boxofficemojo_rankings.csv", "")
    csv_path = os.path.join(DATA_DIR, filename)
    this_df = pd.read_csv(csv_path)
    this_df['filename'] = filename
    this_df['year'] = year
    print(this_df.head(n=1))
    my_dataframes.append(this_df)

2010_boxofficemojo_rankings.csv
   Rank Release Group       Worldwide      Domestic      %       Foreign  \
0     1   Toy Story 3  $1,066,969,703  $415,004,880  38.9%  $651,964,823

     %.1                         filename  year
0  61.1%  2010_boxofficemojo_rankings.csv  2010
2017_boxofficemojo_rankings.csv
   Rank                            Release Group       Worldwide  \
0     1  Star Wars: Episode VIII - The Last Jedi  $1,332,539,889

       Domestic      %       Foreign    %.1                         filename  \
0  $620,181,382  46.5%  $712,358,507  53.5%  2017_boxofficemojo_rankings.csv

   year
0  2017
2016_boxofficemojo_rankings.csv
   Rank               Release Group       Worldwide      Domestic      %  \
0     1  Captain America: Civil War  $1,153,296,293  $408,084,349  35.4%

        Foreign    %.1                         filename  year
0  $745,211,944  64.6%  2016_boxofficemojo_rankings.csv  2016
2011_boxofficemojo_rankings.csv
   Rank                                 Release Group       Worldwide  \
0     1  Harry Potter and the Deathly Hallows: Part 2  $1,341,511,219

       Domestic      %       Foreign    %.1                         filename  \
0  $381,011,219  28.4%  $960,500,000  71.6%  2011_boxofficemojo_rankings.csv

   year
0  2011
2018_boxofficemojo_rankings.csv
   Rank           Release Group       Worldwide      Domestic      %  \
0     1  Avengers: Infinity War  $2,048,359,754  $678,815,482  33.1%

          Foreign    %.1                         filename  year
0  $1,369,544,272  66.9%  2018_boxofficemojo_rankings.csv  2018
2014_boxofficemojo_rankings.csv
   Rank                    Release Group       Worldwide      Domestic      %  \
0     1  Transformers: Age of Extinction  $1,104,054,072  $245,439,076  22.2%

        Foreign    %.1                         filename  year
0  $858,614,996  77.8%  2014_boxofficemojo_rankings.csv  2014
2013_boxofficemojo_rankings.csv
   Rank Release Group       Worldwide      Domestic      %       Foreign  \
0     1        Frozen  $1,280,802,282  $400,738,009  31.3%  $880,064,273

     %.1                         filename  year
0  68.7%  2013_boxofficemojo_rankings.csv  2013
2012_boxofficemojo_rankings.csv
   Rank Release Group       Worldwide      Domestic    %       Foreign  %.1  \
0     1  The Avengers  $1,518,812,988  $623,357,910  41%  $895,455,078  59%

                          filename  year
0  2012_boxofficemojo_rankings.csv  2012
2019_boxofficemojo_rankings.csv
   Rank      Release Group       Worldwide      Domestic      %  \
0     1  Avengers: Endgame  $2,797,800,564  $858,373,000  30.7%

          Foreign    %.1                         filename  year
0  $1,939,427,564  69.3%  2019_boxofficemojo_rankings.csv  2019
2015_boxofficemojo_rankings.csv
   Rank                               Release Group       Worldwide  \
0     1  Star Wars: Episode VII - The Force Awakens  $2,068,223,624

       Domestic      %         Foreign    %.1  \
0  $936,662,225  45.3%  $1,131,561,399  54.7%

                          filename  year
0  2015_boxofficemojo_rankings.csv  2015
2020_boxofficemojo_rankings.csv
   Rank      Release Group     Worldwide  Domestic      %       Foreign  \
0     1  The Eight Hundred  $441,656,664  $331,279  <0.1%  $441,325,385

     %.1                         filename  year
0  99.9%  2020_boxofficemojo_rankings.csv  2020

In [17]:
my_entire_dataframe = pd.concat(my_dataframes)

In [18]:
my_entire_dataframe.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,Toy Story 3,"$1,066,969,703","$415,004,880",38.9%,"$651,964,823",61.1%,2010_boxofficemojo_rankings.csv,2010
1,2,Alice in Wonderland,"$1,025,467,110","$334,191,110",32.6%,"$691,276,000",67.4%,2010_boxofficemojo_rankings.csv,2010
2,3,Harry Potter and the Deathly Hallows: Part 1,"$976,536,918","$295,983,305",30.3%,"$680,553,613",69.7%,2010_boxofficemojo_rankings.csv,2010
3,4,Inception,"$826,137,188","$292,576,195",35.4%,"$533,560,993",64.6%,2010_boxofficemojo_rankings.csv,2010
4,5,Shrek Forever After,"$752,600,867","$238,736,787",31.7%,"$513,864,080",68.3%,2010_boxofficemojo_rankings.csv,2010

In [19]:
my_entire_dataframe.tail()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
245,246,The Fox Hunter,"$1,577","$1,577",100%,-,-,2020_boxofficemojo_rankings.csv,2020
246,247,Fear Pharm,"$1,157","$1,157",100%,-,-,2020_boxofficemojo_rankings.csv,2020
247,248,Hai Tang Hong,"$1,107","$1,107",100%,-,-,2020_boxofficemojo_rankings.csv,2020
248,249,Greater 2020 Re-release,$527,$527,100%,-,-,2020_boxofficemojo_rankings.csv,2020
249,250,Spaceship Earth,$362,-,-,$362,100%,2020_boxofficemojo_rankings.csv,2020

In [21]:
dataset = os.path.join(CACHE_DIR, 'box-office-ranking-dataset.csv')
my_entire_dataframe.to_csv(dataset)